site_name: travis.stallaf.net
site_url: https://travis.stallaf.net/
site_author: SF aka stallaf
site_description: Traduction en français de la documentation de TRAVIS CI.

theme: 
   name: readthedocs
   locale: fr
   highlightjs: true             # coloration du code source
   hljs_languages:               # langages utilisés
      - yaml
      - html
      - php
      - md
      - json
      - bash
      - shell
      - css
      - ini
      - txt
      - twig
      - console
   sticky_navigation: false      # le menu reste fixe

extra_css:
   - css/base.css         # pour la prise en charge du css personalisé
    
nav:
  - 1. Démarrage:
    - Bienvenue: bienvenue.md
    - Embarquement pour Travis CI: embarquement.md
    - Concepts de base pour les débutants: concepts-de-base-pour-debutants.md
    - Personnalisation de la construction: personnalisation-de-la-construction.md
    - Accélération de la construction: acceleration-de-la-construction.md
    - Utilisation de Docker: utilisation-de-docker.md
    - Tests avec des navigateurs: tests-avec-des-navigateurs.md
    - Construction de PR: construction-de-demande-de-tirage.md
    - Tâches cron: taches-cron.md
    - Problèmes courants de construction: problemes-courants-de-construction.md
    - Client en ligne de commande: client-en-ligne-de-commande.md
    - Importer une configuration de construction partagée: importer-une-configuration-de-build-partagee.md
    - Validation de configuration de la construction: validation-configuration-de-la-construction.md
  - 2. Tutoriels:
    - Vue d'ensemble: apercu-tutoriels.md
    - Tutoriel C/C++: tutoriel-c-c++.md
    - Tutoriel Java: tutoriel-java.md
    - Tutoriel Node.js: tutoriel-nodejs.md
    - Tutoriel Python: tutoriel-python.md
    - Tutoriel Ruby: tutoriel-ruby.md
  - 3. Tâches, builds, matrices et étapes: 
    - Cycle de vie d'une tâche: cycle-de-vie-de-job.md
    - Matrice de construction: matrice-de-construction.md
    - Etapes de construction: etapes-de-construction.md
    - Constructions conditionnelles, étapes et tâches: constructions-conditionnelles.md
  - 4. Installation des dépendances: 
    - Installation-des-dependances : installation-des-dependances.md
    - Dépendances privées GitHub: dependances-privees-github.md
    - Dépendances privées BitBucket: dependances-privees-bitbucket.md
    - Configuration de BDD et de services: configurer-bdd-et-services.md
    - Dépendances et répertoires du cache: dependances-et-repertoires-du-cache.md

not_in_nav: | 
   index.md
   a-propos.md
   mentions-legales.md

exclude_docs: |


